FROM debian:10.2-slim

RUN mkdir -p /app/data && chown nobody:nogroup /app/data

COPY bee-clef /usr/local/bin/bee-clef
COPY packaging/rules.js /app/config/rules.js
COPY packaging/4byte.json /app/config/4byte.json
COPY packaging/docker/entrypoint.sh /entrypoint.sh

EXPOSE 8550
USER nobody
WORKDIR /app
VOLUME /app/data

ENTRYPOINT ["/entrypoint.sh"]
