#!/usr/bin/env sh

start() {
    KEYSTORE=/usr/local/var/lib/swarm-clef/keystore
    CONFIGDIR=/usr/local/var/lib/swarm-clef
    CHAINID=5
    SECRET=$(cat /usr/local/var/lib/swarm-clef/password)
    ( sleep .5; cat << EOF
{ "jsonrpc": "2.0", "id":1, "result": { "text":"$SECRET" } }
EOF
) | /usr/local/bin/clef --stdio-ui --keystore $KEYSTORE --configdir $CONFIGDIR --chainid $CHAINID --rules /usr/local/etc/swarm-clef/rules.js --nousb --4bytedb-custom /usr/local/etc/swarm-clef/4byte.json --pcscdpath "" --auditlog "" --loglevel 3 --ipcpath /usr/local/var/lib/swarm-clef
}

stop() {
    echo "STOP! System will stop the service!"
}

case $1 in
    start|stop) "$1"
esac